# dictionary object containing trigger words and responses
phrases = {'alex': ['what do you mean', 'blimey', 'lemons'],
           'beans': 'Alex Beans',
           'shit': 'Shit on a donkey',
           'goose': ["Honk", "You wouldn't say boo to a goose"],
           'donkey': ['Shit on it', 'Donkey'],
           'bugger it': ['*slaps thigh*', '*pours whisky*'],
           'aiimi': ['Llamas in a field of sheep',
                     'ooooooooooh, connecting people to insight'],
           'trigger': ['*Explodes*', 'Trigger Warning'],
           'tea': ["Smashed a fucking mug"],
           'nine': ['NIIIINE', 'Nine', '9'],
           '9': ['NIIIINE', 'Nine', '9'],
           'paper': "<@149666799321874434> I've run out of paper",
           'taylor swift': '*play I knew you were trouble',
           'Hi': ["Hiiiiiii, I'm Stoaga"],
           'that is the thing': 'this is the thing',
           'this is the thing': 'that is the thing'}
